/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NaiveConfigProvider: typeof import('./../components/naive/NaiveConfigProvider.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeProvider: typeof import('./../components/theme/ThemeProvider.vue')['default']
  }
}
